function responseFormat = getDefaultFormat()
    responseFormat = struct( ...
        "is_toc", false, ...
        "is_register_summary_relevant", false, ...
        "is_register_map_relevant", false, ...
        "is_digital_interface_relevant", false, ...
        "is_data_conversion_relevant", false, ...
        "is_initialization_and_reset_relevant", false, ...
        "is_timing_relevant", false, ...
        "is_interrupt_alert_relevant", false, ...
        "is_fifo_relevant", false, ...
        "is_coding_example", false);
end

