function responseFormat = getDescriptionFormat()
    responseFormat = struct( ...
    'toc', "", ...
    'register_summary', "", ...
    'register_map', "", ...
    'digital_interface', "", ...
    'data_conversion', "", ...
    'initialization_and_reset', "", ...
    'timing', "", ...
    'interrupt_alert', "", ...
    'fifo', "", ...
    'coding_example', "" ...
    );
end

