function responseFormat = getRegMapDefaultFormat()
%RESPONSEFORMAT Summary of this function goes here
%   Detailed explanation goes here
addressStr = struct( ...
    'hex', "", ...
    'decimal', "", ...
    'bank', "", ...
    'page', "" ...
    );

valueStr(1) = struct( ...
    'value', "", ...
    'value_description', "" ...
    );

valueStr(2) = struct( ...
    'value', "", ...
    'value_description', "" ...
    );

fieldStr(1) = struct( ...
    'name_or_parameter', "", ...
    'field_description', "", ...
    'bit_start', 0, ...
    'bit_end', 0, ...
    'bit_width', 0, ...
    'values', valueStr, ...
    'is_reserved', false, ...
    'type_write_read', "" ...
    );

fieldStr(2) = struct( ...
    'name_or_parameter', "", ...
    'field_description', "", ...
    'bit_start', 0, ...
    'bit_end', 0, ...
    'bit_width', 0, ...
    'values', valueStr, ...
    'is_reserved', false, ...
    'type_write_read', "" ...
    );

sourceStr(1) = struct( ...
    'page_index', 0 ...
    );

sourceStr(2) = struct( ...
    'page_index', 0 ...
    );

registerStr(1) = struct( ...
    'index', 0, ...
    'name', "", ...
    'address', addressStr, ...
    'register_description', "", ...
    'width_bits', 0, ...
    'type_write_read', "", ...
    'bit_field', fieldStr, ...
    'category', "", ...
    'source', sourceStr, ...
    'default_value', "", ...
    'default_value_description', "" ...
    );

registerStr(2) = struct( ...
    'index', 0, ...
    'name', "", ...
    'address', addressStr, ...
    'register_description', "", ...
    'width_bits', 0, ...
    'type_write_read', "", ...
    'bit_field', fieldStr, ...
    'category', "", ...
    'source', sourceStr, ...
    'default_value', "", ...
    'default_value_description', "" ...
    );

responseFormat = struct( ...
    'Registers', registerStr ...
    );
end

